### ISSUE TITLE
[question] difference with Leaflet.fullscreen

### ISSUE THREAD

**Issue by francoisromain** [brunob/leaflet.fullscreen#68]
Hello and thank you for investing time on this project. 
Could you please explain the difference with this project: https://github.com/Leaflet/Leaflet.fullscreen ?

**Comment by brunob** [comment]
No real difference, just than mapbox have created a dupplicate of this project instead of cooperate. This is not the first time i've been facing this in leaflet community, see these repos i've finally archived for exemple : https://github.com/brunob/leaflet.draw.archive & https://github.com/brunob/leafclusterer.archive and today i'm facing it again with kml plugin here https://github.com/shramov/leaflet-plugins/issues/289

libre != open source ^^

Closing the issue but feel free to comment if needed :)
